[pytest]
addopts =
    --headed
    --browser chromium
    --video=retain-on-failure
    --screenshot=only-on-failure
    --html=myreport.html
    --tracing=retain-on-failure
    --alluredir=reports/allure-results